# Generated by Django 4.2.1 on 2025-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'status', 'check_in', 'check_out'], name='core_bookin_listing_e4cf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', '-created_at'], name='core_listin_city_30cbe7_idx'),
        ),
    ]
