# Generated by Django 5.0.6 on 2025-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
